services:
  # A Docker web service
  - type: web
    name: Ngrok
    env: docker
    repo: https://github.com/93871nnm539q/Railway-Ngrok.git # optional
    region: Singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80
      - key: NGROK_TOKEN
        value: 2BNYe4xsXCokZifdoMkzW1bnW6C_5R2Nxk7HsgQvd4swywSPP
      - key: REGION
        value: us
